apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData :   #Yes, you can pass admin directly using stringData — encoding is only required when using data
  USERNAME: admin
  PASSWORD: admin

# cmd to create manually
# kubectl create secret generic app-secret \
#   --from-literal=USERNAME=admin \
#   --from-literal=PASSWORD=password
